In [25]:
# Set own library path
import sys
sys.path.append('/Users/guillemmirabentrubinat/Library/CloudStorage/OneDrive-Personal/BSE/CDS Computing for Data Science/Problem Sets/hw3/Computing-for-DS-HW2/GMR_lib1')

# Import Libraries

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from GMR_lib1.module1 import nan_remover

# Import Dataset

data = pd.read_csv('sample_diabetes_mellitus_data.csv')
display(data)

ImportError: cannot import name 'nan_remover' from 'GMR_lib1.module1' (/Users/guillemmirabentrubinat/.pyenv/versions/3.12.0/envs/hw3/lib/python3.12/site-packages/GMR_lib1/module1.py)

In [20]:
# Cleaning the data using the functions from the library
data_safecopy = data

gmr.nan_remover(data, ['age', 'gender', 'ethnicity'])
display(data)

AttributeError: module 'GMR_lib1.module1' has no attribute 'nan_remover'

In [19]:
# Split the data between train and test

X_train, X_test, y_train, y_test = train_test_split(
    data.drop('diabetes_mellitus', axis=1),
    data['diabetes_mellitus'],
    test_size=0.2,
    random_state=42
    )

#X_train.head()
#X_test.head()
#print(len(y_train))
#print(y_test)

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,urineoutput_apache,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis
6252,6252,275141,81,66.0,34.852863,0,Caucasian,M,180.3,Emergency Department,...,NaN,1,7.6,0,0,0,0,0,0,0
4684,4684,269942,118,NaN,18.593750,0,Caucasian,F,160.0,NaN,...,NaN,0,6.9,0,0,0,0,0,0,0
1731,1731,183562,118,83.0,28.215375,0,Caucasian,F,154.9,Other Hospital,...,NaN,1,19.6,0,0,0,0,0,0,0
4742,4742,244929,118,64.0,21.575502,1,Caucasian,F,170.2,Emergency Department,...,NaN,0,10.0,0,0,0,1,0,0,0
4521,4521,193781,118,21.0,34.560280,1,African American,F,162.0,Operating Room,...,NaN,1,18.0,0,0,0,0,0,0,0