In [8]:
# Set own library path
import sys
sys.path.append('/Users/guillemmirabentrubinat/Library/CloudStorage/OneDrive-Personal/BSE/CDS Computing for Data Science/Problem Sets/hw3/Computing-for-DS-HW2/GMR_lib1')

# Import Libraries

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import GMR_lib1 as gmr

# Import Dataset

data = pd.read_csv('/Users/guillemmirabentrubinat/Library/CloudStorage/OneDrive-Personal/BSE/CDS Computing for Data Science/Problem Sets/hw3/Computing-for-DS-HW2/sample_diabetes_mellitus_data.csv')
display(data)

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
0,0,214826,118,68.0,22.732803,0,Caucasian,M,180.30,Floor,...,0,14.1,0,0,0,0,0,0,0,1
1,1,246060,81,77.0,27.421875,0,Caucasian,F,160.00,Floor,...,1,12.7,0,0,0,0,0,0,0,1
2,2,276985,118,25.0,31.952749,0,Caucasian,F,172.70,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
3,3,262220,118,81.0,22.635548,1,Caucasian,F,165.10,Operating Room,...,1,8.0,0,0,0,0,0,0,0,0
4,4,201746,33,19.0,NaN,0,Caucasian,M,188.00,NaN,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,167042,140,NaN,51.952814,0,Caucasian,F,137.20,Floor,...,0,7.0,0,0,0,0,0,0,0,0
9996,9996,165009,89,34.0,26.110113,0,Caucasian,F,175.26,Emergency Department,...,0,9.5,0,0,0,0,0,0,0,0
9997,9997,234052,137,30.0,23.774241,0,Native American,F,157.48,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
9998,9998,249290,89,67.0,31.330708,0,Caucasian,F,157.48,Direct Admit,...,0,6.4,0,0,0,0,0,0,0,0
9999,9999,151312,89,55.0,44.343663,0,Caucasian,F,157.50,Emergency Department,...,1,NaN,0,0,0,0,0,0,0,0

In [12]:
# Cleaning the data using the functions from the library
data_safecopy = data

# We clean the rows that have missing data in the columns age, gender and ethnicity
data = gmr.nan_remover(data, ['age', 'gender', 'ethnicity'])
display(data) # to check that the total number of rows has decreased

# We check the total number of missing values in the column height
nan_in_height = data['height'].isnull().sum()
print(nan_in_height)
# We fill missing values of columns height and weight with the mean of the column
data = gmr.nan_filler(data, ['height', 'weight'])
# We check that the total number of missing values in 'height' is now 0
nan_in_height2 = data['height'].isnull().sum()
print(nan_in_height2)

# Generate the one hot encoding for the ethnicity column and print the head() again to check the newly created columns
data = gmr.one_hot(data, )

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
0,0,214826,118,68.0,22.732803,0,Caucasian,M,180.30,Floor,...,0,14.1,0,0,0,0,0,0,0,1
1,1,246060,81,77.0,27.421875,0,Caucasian,F,160.00,Floor,...,1,12.7,0,0,0,0,0,0,0,1
2,2,276985,118,25.0,31.952749,0,Caucasian,F,172.70,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
3,3,262220,118,81.0,22.635548,1,Caucasian,F,165.10,Operating Room,...,1,8.0,0,0,0,0,0,0,0,0
4,4,201746,33,19.0,NaN,0,Caucasian,M,188.00,NaN,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,9994,271449,89,78.0,28.700475,0,Caucasian,F,172.70,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
9996,9996,165009,89,34.0,26.110113,0,Caucasian,F,175.26,Emergency Department,...,0,9.5,0,0,0,0,0,0,0,0
9997,9997,234052,137,30.0,23.774241,0,Native American,F,157.48,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
9998,9998,249290,89,67.0,31.330708,0,Caucasian,F,157.48,Direct Admit,...,0,6.4,0,0,0,0,0,0,0,0
9999,9999,151312,89,55.0,44.343663,0,Caucasian,F,157.50,Emergency Department,...,1,NaN,0,0,0,0,0,0,0,0

127
0

In [19]:
# Split the data between train and test

X_train, X_test, y_train, y_test = train_test_split(
    data.drop('diabetes_mellitus', axis=1),
    data['diabetes_mellitus'],
    test_size=0.2,
    random_state=42
    )

#X_train.head()
#X_test.head()
#print(len(y_train))
#print(y_test)

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,urineoutput_apache,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis
6252,6252,275141,81,66.0,34.852863,0,Caucasian,M,180.3,Emergency Department,...,NaN,1,7.6,0,0,0,0,0,0,0
4684,4684,269942,118,NaN,18.593750,0,Caucasian,F,160.0,NaN,...,NaN,0,6.9,0,0,0,0,0,0,0
1731,1731,183562,118,83.0,28.215375,0,Caucasian,F,154.9,Other Hospital,...,NaN,1,19.6,0,0,0,0,0,0,0
4742,4742,244929,118,64.0,21.575502,1,Caucasian,F,170.2,Emergency Department,...,NaN,0,10.0,0,0,0,1,0,0,0
4521,4521,193781,118,21.0,34.560280,1,African American,F,162.0,Operating Room,...,NaN,1,18.0,0,0,0,0,0,0,0